services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    ports:
      - ${OVERSEERR_PORT}:5055
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
      - PORT=5055 # optional
    volumes:
      - ./config/overseer:/app/config

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8081:8080 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port
      - 9696:9696 # prowlarr
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 8787:8787 # readarr
    volumes:
      - media_gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - TZ=${TZ}
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - ./config/qbittorrent:/config
      - ${MEDIA_DATA}:/data

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - ./config/prowlarr:/config
      - ${MEDIA_DATA}:/data
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - ./config/radarr:/config
      - ${MEDIA_DATA}:/data
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    volumes:
      - ./config/sonarr:/config
      - ${MEDIA_DATA}:/data
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}

  readarr:
    image: ghcr.io/hotio/readarr
    container_name: readarr
    restart: unless-stopped
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=${TZ}
    volumes:
      - ./config/readarr:/config
      - ${MEDIA_DATA}:/data

volumes:
  media_gluetun:
