services:
  commafeed:
    image: athou/commafeed:5.8.0-postgresql
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/${COMMAFEED_DB_NAME}
      - QUARKUS_DATASOURCE_USERNAME=${COMMAFEED_DB_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${COMMAFEED_DB_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
     - ${PORT}:8082

  postgresql:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${COMMAFEED_DB_USER}
      POSTGRES_PASSWORD: ${COMMAFEED_DB_PASSWORD}
      POSTGRES_DB: ${COMMAFEED_DB_NAME}
    volumes:
      - commafeed_postgresql:/var/lib/postgresql/data

  commafeed_postgresql_backup:
    image: offen/docker-volume-backup:v2
    restart: unless-stopped
    environment:
      BACKUP_CRON_EXPRESSION: "${BACKUP_CRON_EXPRESSION}"
      BACKUP_RETENTION_DAYS: "${BACKUP_RETENTION_DAYS}"
      BACKUP_FILENAME: "${BACKUP_FILENAME}"
    volumes:
      - commafeed_postgresql:/backup/source:ro
      - ${BACKUP_DIRECTORY}:/backup/dest # Local backup destination

volumes:
  commafeed_postgresql:

